# prokka params
centre: "UU"
minlen: "200"
genus: "Escherichia"
species: "coli"

# RGI params
filter_criterion: "Loose"

# regions_coords params
span: 100000
min_plasmid_size: 1000

# direct_repeats params
mode: 2
min_size: 20
format: 1
mism: 0
seed_mism: 0
max_dist: 205000
min_dist: 100

# dr_annotation params
min_repeat_length: 20