# trim_illumina params
quality: "20"
window_size: "4"
cut_right: "20"
length_required: "50"
trim_front: "10"

# trim_nanopore params
min_nanopore_length: 3000

# adaptive_hybrid_assembly params
basecaller: "r941_min_fast_g507"
genome_size: "5m"
coverage: 50
genome_length: 5131220
cov_threshold: 30

# qc_assembly params
tax_dataset: "gammaproteobacteria_odb10"

# assembly_summary params
position: 2
