# choose which part of the pipeline to run
run_assembly: False
run_annotation: False
run_mutants: False
run_phylogeny: False

# if assembly has been run before mutants, set this to False
trim_parents: True

default_container: "resources/singularity/default.sif"
biopython_container: "resources/singularity/biopython.sif"
assembly_container: "resources/singularity/assembly.sif"