# strain names
parents: "config/mutants_test.txt"

# raw reads (mutants) path
mutants_path: "data/mutants"
parents_path: "data/parents"
 
# qual and BGI-adapters trimming
trim_front: 10
adapter1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
adapter2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG

# var.calling
max_depth: 800
ploidy: 1
prior: "5.0e-10"

# var.filtering
indel_dist: 3
quality: 30
depth: 20

# over-covered regions, a.k.a. amplifications
z_threshold: 3
window_size: 1000

# raltive coverage
min_contig_len: 1000
